// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxcjllnkktfysnrsgxtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54Y2psbG5ra3RmeXNucnNneHRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTI5NjksImV4cCI6MjA2MzI2ODk2OX0.CQDXa1Al1oFBa307YnlykJ_ioTUbk_nHxPDUVAgJZNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);